//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dating_data.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int User1 { get; set; }
        public int User2 { get; set; }
        public int FriendId { get; set; }
        public bool status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User3 { get; set; }
    }
}
