//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dating_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int DescriptionId { get; set; }
        public string Description1 { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string AboutMe { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual User User { get; set; }
    }
}
